#!/bin/bash

SOURCE="$HOME/.config/nvim"

echo -n "Updating files..."

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
	echo ""
    echo "error: the script is not in a git repo."
    exit 1
fi

mkdir -p config/
rm -rf config/*
cp -r "$SOURCE/lua" "$SOURCE/init.lua" config/

echo " done."

git status --ignored
